import { CHECKER_PATH, LOCK_PATH, WORKFLOW_PATH } from "./constants";

/**
 * The verifier written into each consuming repository.
 *
 * Plain Node ESM on purpose: it runs in CI and on contributors' machines,
 * where Bun is not a given but Node is present on every GitHub runner. It
 * takes no arguments, reads no network, and installs nothing — the whole
 * point is that a clone can verify itself.
 *
 * It checks only the paths named in the lock, so a repository's own
 * project-specific rules can live in `.claude/rules/` untouched and never
 * trip the check.
 */
export const CHECKER_SOURCE = `#!/usr/bin/env node
// Generated by the claude-rules plugin. Do not edit.
// Verifies that vendored rules still match .claude/rules-lock.json.
// Regenerate with /claude-rules:update — never by hand.
import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const claudeDir = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(claudeDir, "..");
const lockPath = join(projectRoot, "${LOCK_PATH}");

const digest = (contents) =>
  "sha256-" +
  createHash("sha256").update(contents.replace(/\\r\\n/g, "\\n")).digest("hex");

const lockRaw = await readFile(lockPath, "utf8").catch(() => null);
if (lockRaw === null) {
  console.error("rules-check: ${LOCK_PATH} not found — run /claude-rules:update");
  process.exit(1);
}

const lock = JSON.parse(lockRaw);
const missing = [];
const modified = [];

for (const [relativePath, expected] of Object.entries(lock.files ?? {})) {
  const contents = await readFile(join(projectRoot, relativePath), "utf8").catch(
    () => null,
  );
  if (contents === null) {
    missing.push(relativePath);
    continue;
  }
  if (digest(contents) !== expected) {
    modified.push(relativePath);
  }
}

if (missing.length === 0 && modified.length === 0) {
  const count = Object.keys(lock.files ?? {}).length;
  console.log(\`rules-check: \${count} vendored files match \${lock.source}@\${lock.version}\`);
  process.exit(0);
}

console.error("rules-check: vendored rules do not match the lock.\\n");
for (const path of missing) console.error(\`  missing:  \${path}\`);
for (const path of modified) console.error(\`  modified: \${path}\`);
console.error(
  "\\nThese files are vendored from " +
    \`\${lock.source}. Do not edit them here — the change would be \` +
    "overwritten on the next sync and is invisible to every other repo.\\n" +
    "Edit the rule upstream, release it, then run /claude-rules:update.\\n" +
    "To discard local edits and restore the locked content, re-run the sync.",
);
process.exit(1);
`;

/** Optional CI workflow. Written only on `--with-ci`, since not every repo uses Actions. */
export const WORKFLOW_SOURCE = `name: Rules Check

# Generated by the claude-rules plugin. Safe to edit — this file is not locked.
# Fails the build when vendored rules drift from .claude/rules-lock.json.

on:
  push:
    branches: [main]
  pull_request:

jobs:
  rules-check:
    name: Vendored rules match lock
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify vendored rules
        run: node ${CHECKER_PATH}
`;
